# Generated by Django 6.0.6 on 2026-06-17 02:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Jardinero',
                'verbose_name_plural': 'Jardineros',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('garden_area_sqm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área del jardín (m²)')),
                ('preferred_date', models.DateField(verbose_name='Fecha preferida')),
                ('preferred_time_start', models.TimeField(verbose_name='Hora de inicio')),
                ('preferred_time_end', models.TimeField(verbose_name='Hora de término')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de confirmación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('gardener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to='visits.gardener', verbose_name='Jardinero asignado')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_requests', to='visits.servicetype', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Solicitud de Visita',
                'verbose_name_plural': 'Solicitudes de Visita',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='visits_visi_status_ff27e8_idx'), models.Index(fields=['preferred_date'], name='visits_visi_preferr_521bc1_idx'), models.Index(fields=['confirmation_token'], name='visits_visi_confirm_a2e464_idx')],
            },
        ),
    ]
